# Site
title:              Volvo 850 Warwagon
bio:                'Fansite, blog and issue log.'
description:        "Issue and modifaction log. Database of issue/solution articles."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US

# LOCAL - TESTING
# url:              127.0.0.1:4000
# baseurl:          /volvo-850-log
# assets:           /volvo-850-log/assets

# REMOTE - GH-PAGES WITHOUT DOMAIN
url:              http://ackoujens.github.io
baseurl:          /volvo-850-log
assets:           /volvo-850-log/assets

# REMOTE - GH-PAGES WITH DOMAIN
# url:                http://volvo850wagon.tk
# baseurl:
# assets:             /assets

# Limit posts to parse
lsi: false

# Disable custom plugins
safe: false

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  input: GFM
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
#  style:            compressed

# Comments
disqus_shortname:   volvo850wagon

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              ackoujens@gmail.com
twitter:            ackoujens
#facebook:           username
github_username:    ackoujens
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          ackoujens
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
youtube:            UCRtdHn14S8pudL77Mb-hznq
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-coffeescript
  - jekyll-mentions
  - jekyll-feed
#  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    baseurl: /volvo-850-log

# Exclude list
#exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
